import ReduxProvider from './ReduxProvider'
import './global.css'


export const metadata = {
  title: 'News_Application',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
      <html lang="en">
      <body>
      {children}
      </body>
    </html>
    </ReduxProvider>
  )
}
